### ISSUE TITLE
Big Change: Hozkul + Hozlin

### ISSUE THREAD

**Issue by DraaGulFireclaw** [Rackiera/threa#23]
### Big Change: Hozkul, Hozlin and HozReok
The three are supposed to be made more realistic and fit better into Threa.

**To-Do-List**
- [x] Remove Monarchy of the Free Caverns
- [ ] Change HozReok to a kingdom of Hozlin
- [ ] Change Aezkul Republic story, add Hozlin
- [ ] Edit Hozlin anatomy
- [ ] Edit Hozkul anatomy

**Hozkul Anatomy Changes:**
- Hozkul gain new climbing arms, recycled wings basically

**Hozlin Anatomy Changes:**
- Less hunched over maybe? They live underground mostly still, but they also go above ground a lot.

![HozChat](https://user-images.githubusercontent.com/24594841/59871246-5f510200-9397-11e9-8877-f6d025c6e05e.png)

"I am unhappy with the Hozlin and Hozkul.

I love how they look. Their society is cool, too.

I can't shake the feeling that they do not make sense. A highly developed species? Growing underground? It bugs me in a lot of ways. The underground doesn't even provide that much to live off of.

I bugs me so much I've been wondering if to ask you if we could remove Hozlin and Hozkul, and make Subterra less... impossible from a scientific standpoint.

However, I think instead of removing them perhaps making them a lot more primitive would work? Hozlin would basically be the cave trolls of Threa so to speak. :'D They live in caves north of the Starless Jungle, only come out at night to find food and perhaps cross stretches of surface to reach other caves, and are overall low in numbers.

The Hozkul? I am not sure what to do about them. I am wondering if to bring them to the surface and make them some kind of mountain-loving, wingless surface dragon. But they're so huge I am wondering how and if they could live in such a way. Well, that something so huge lives underground makes little sense to begin with.

And yes, I'd have no problem at all with my work that went into making up their history, society and so on and so forth being removed. I'd save the pages and perhaps make one of the bird nations further down the line similar to them, just on the surface.

Heck, another idea is that the Aezkul, because so many Hozlin live in their mountains, have managed to befriend the grey humanoids and Hozlin make up the biggest share of lin servants the Aezkul have. 

It could have been the Hozlin that dug out the fortresses. They could've even partaken in the 1000 years war of the Aezkul. In my opinion that'd be much cooler, but it's just an idea.

--- End ---
Draa Gulheute um 14:43 Uhr
Idea: Hozlin and Aezkul History
While randomly  chatting with Ulk I had an amazing idea for Hozlin and how they interacted with Aezkul.

The Aezkul enslaved each other during the thousand year war, right?

Since slavery didn't appear like an evil concept to Aezkul of old, it isn't all that unlikely that the Aezkul enslaved the Hozlin. They make great workers after all and I imagine the Hozlin originally evolved in the Aezrikka Zule anyway.

So, I imagine the following series of events:

1. Thre Wind Kingdoms enslave Hozlin. Hozlin workers dig homes and fortresses of their Aezkul overlords. Aezkul are strict and firm, but overall firm and not tyrannical.

2. The Wind Kingdoms flourish. Their explorers and scholars spread across the world, make maps, produce tomes, try to make sense of it all. Their beloved divine wind carries them to new frontiers. They erect outposts wherever possible by bringing their Hozlin slaves with them to dig them into Threa's mountain ranges.

3. The Wind Kingdoms wage war against each other. The 1000 Year War begins; Hozlin serve as warriors on foot. As more and more Aezkul fall to the fighting in the Zule, more and more outposts are abandoned to replenish the numbers back home. In their haste to return home, the Aezkul leave behind most of their Hozlin servants.

4. Aezkul history basically goes on as we know it, just with Hozlin sprinkled in. Meanwhile the abandoned Hozlin start primitive societies of their own in the mountains and just try to get by without their overlords.

5. After the war, the Aezkul start treating the Hozlin better as well as they experience a surge of ethics within their Republic.

Combining the Aezkul and Hozlin feels like a really cool dynamic. The sky meets the underground. Huge cities dug into mountains by Hozlin laborers, inhabited by Aezkul scholars, soldiers, hunters, explorers, and rulers.

Idea End"

**Comment by DraaGulFireclaw** [comment]
This issue is no longer relevant due to the Threa Rework.

It can still serve as a nice source of ideas for the Hozlin and Hozkul.
